version: "3.8"

services:
  backend:
    build: ./backend/

  db:
    container_name: lhb-backend-db
    image: postgres:12
    restart: always
    volumes:
      - ./docker/postgres-setup:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - external

networks:
  external:
    external: true